# -*- coding: utf-8 -*-
"""chandana sree (20221cit0058)exp-06(26/03/24)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FEu11Gbex892JksXPyEKOyY2vdl9ohf
"""

import pandas as pd
df = pd.read_csv('/content/train.csv')
df.isna().sum

age_mean_value=df['Age'].mean()

df['Age']=df['Age'].fillna(age_mean_value)

df.drop("Cabin",axis=1,inplace=True)

df.head()

filtered_age = df[df.Age>40]
filtered_age

sorted_passengers = df.sort_values('Name',ascending=True,kind='heapsort')
sorted_passengers.head(10)

merged_df = pd.merge(df.head(2),df.tail(2),how='outer',indicator=True)
merged_df

group_df=df.groupby('Name')

for key, item in group_df:
  print(group_df.get_group(key),"\n\n")

