# -*- coding: utf-8 -*-
"""chandana sree(20221cit0058)date=07-02-2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcpvQNuLwEKkKvP4VIJ_4hkfKwqRBCgy
"""

!pip install matplotlib==3.4

from matplotlib import pyplot as plt
plt.style.use('seaborn-whitegrid')

import numpy as np
print("step1")

fig=plt.figure()
ax=plt.axes()
ax.grid()

fig=plt.figure()
ax=plt.axes()
x=np.linspace(0,10,100)
ax.plot(x,np.sin(x),label='sin')
ax.plot(x,np.cos(x),label='cos')
ax.set_title('Multiple Line');
ax.set_xlabel('xlabel')
ax.set_ylabel('ylabel')
ax.legend();
#ax.legend(loc=1)
plt.show()

fig=plt.figure()
ax=plt.axes()
x=np.linspace(0,10,1000)
ax.plot(x,np.sin(x),label='sin',linestyle='dashed')
ax.plot(x,np.cos(x),label='cos',linestyle='dotted')
ax.plot(x,np.sin(x+1),label='cos',linestyle='dashdot')
ax.set_title('Multiple Line');
ax.set_xlabel('xlabel')
ax.set_ylabel('ylabel')
ax.legend();
#ax.legned(loc=1)
plt.show()