# -*- coding: utf-8 -*-
"""chandana sree.20221cit0058 exp-03 (05-03-2024)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_XEJ7a_0umtBmwYX5eNRYpQdcaBtRAM
"""

import pandas as pd

meteorites=pd.read_csv('/content/nasasopendata/Meteorite_Landings_20240305.csv',nrows=5)
meteorites

meteorites.name

meteorites.columns

meteorites.index

import pandas as pd

meteorites = pd.read_csv('/content/nasasopendata/Meteorite_Landings_20240305.csv')

import requests
response = requests.get(
    'https://data.nasa.gov/resource/gh4g-9sfh.json',
    params={'$limit':50_000}
)
if response.ok:
  payload = response.json()
else:
  print(f'Requset was not successful and returned code:{response.status_code}.')
  payload = None

import pandas as pd

df = pd.DataFrame(payload)
df.head(3)

meteorites.shape

meteorites.dtypes

meteorites.head()

meteorites.info()

meteorites[['name', 'mass (g)']]

meteorites[100:104]

meteorites.iloc[100:104, [0, 3, 4, 6]]

meteorites.loc[100:104, 'mass (g)':'year']

(meteorites['mass (g)'] > 50) & (meteorites.fall == 'Found')