# -*- coding: utf-8 -*-
"""chandana sree.20221cit0058(12-03-2024) exp-04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXjF8EzbOPZnO-_7cgK_nc9sXS0xR9Cg
"""

import requests

!pip install --upgrade 'library'

r = requests.get('https://www.romexchange.com/')

r

r.status_code

url='https://www.romexchange.com/'

headers = {'Content-type':'application/json'}

url

headers

url = 'https://www.romexchange.com/'

headers = {'user-agent': 'XY','Content-type':'application/json'}
r = requests.get(url, headers=headers)

r.text

