# -*- coding: utf-8 -*-
"""chandana sree 20221cit0058 exp=07(16/4/24)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hog-h0DqZdCVJGF5NBrQ4tojz8izEW-8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

cars_data = pd.read_csv("/content/Untitled Folder/archive.zip", index_col = 0, na_values = ['??','???'] )

cars_data.info()

cars_data.dropna(axis=0,inplace=True)
cars_data

plt.scatter(cars_data['Age'],cars_data['Price'],c='red')
plt.title('Scatter plot of price vs Age')
plt.xlabel('Age(month)')
plt.ylabel('Price(Euros)')
plt.show()

plt.hist(cars_data['KM'])

plt.hist(cars_data['KM'],color='green',edgecolor='white',bins=30)
plt.title('Histogram of KM')
plt.xlabel('Kilometers')
plt.ylabel('Frequency')
plt.show()

counts = [979, 120, 2]
fueltype = ('Petrol','Disel','CNG')
index = np.arange(len(fueltype))

plt.bar(index,counts,color=['red','blue','cyan'])
plt.title('Bar plot of fuel type')
plt.xlabel('Fuel Types')
plt.ylabel('Frequency')
plt.xticks(index, fueltype, rotation = 60)
plt.show